import mongoose from "mongoose";

const userSchema=new mongoose.Schema({
    name:{
        type:String,
        required:true
    },
    email:{
        type:String,
        required:true,
        unique:true
    },
    password:{
        type:String,
        required:true
    },
    assistantName:{
        type:String
    },
     assistantImage:{
        type:String
    },
    history:[
        {type:String}
    ],
    voiceSettings:{
        speed:{
            type:Number,
            default:1,
            min:0.1,
            max:10
        },
        pitch:{
            type:Number,
            default:1,
            min:0,
            max:2
        },
        volume:{
            type:Number,
            default:1,
            min:0,
            max:1
        },
        language:{
            type:String,
            default:'en-US'
        },
        voiceGender:{
            type:String,
            default:'female',
            enum:['male','female','neutral']
        },
        // Enhanced voice controls
        emphasis:{
            type:String,
            default:'normal',
            enum:['reduced','normal','strong']
        },
        breathiness:{
            type:Number,
            default:0.5,
            min:0,
            max:1
        },
        roughness:{
            type:Number,
            default:0.5,
            min:0,
            max:1
        },
        voiceStyle:{
            type:String,
            default:'neutral',
            enum:['neutral','cheerful','empathetic','calm','assistant','newscast','customerservice']
        },
        speakingStyle:{
            type:String,
            default:'general',
            enum:['general','advertisement','narration','sports','poetry','lyrical']
        },
        noiseReduction:{
            type:Boolean,
            default:true
        },
        autoSpeedAdjust:{
            type:Boolean,
            default:false
        }
    },
    nlpSettings:{
        contextMemory:{
            type:Boolean,
            default:true
        },
        emotionalIntelligence:{
            type:Boolean,
            default:true
        },
        personalityMode:{
            type:String,
            default:'friendly',
            enum:['friendly','professional','casual','formal','enthusiastic','calm','witty','supportive']
        },
        // Enhanced NLP features
        sentimentAnalysis:{
            type:Boolean,
            default:true
        },
        intentRecognition:{
            type:Boolean,
            default:true
        },
        multiTurnConversation:{
            type:Boolean,
            default:true
        },
        languageDetection:{
            type:Boolean,
            default:true
        },
        contextualUnderstanding:{
            type:Boolean,
            default:true
        },
        proactiveAssistance:{
            type:Boolean,
            default:false
        },
        learningMode:{
            type:Boolean,
            default:true
        },
        conversationMemoryLength:{
            type:Number,
            default:10,
            min:5,
            max:50
        }
    }

},{timestamps:true})

const User=mongoose.model("User",userSchema)
export default User